create table news_articles (
    id bigint generated by default as identity primary key,
    title varchar(300) not null,
    source varchar(80),
    url varchar(1000),
    body text,
    language varchar(16),
    published_at timestamptz,
    hash char(64) not null unique,
    created_at timestamptz not null default now()
);

create table analysis_runs (
    id bigint generated by default as identity primary key,
    news_id bigint not null references news_articles(id),
    status varchar(16) not null
        check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
    model_version varchar(64) not null,
    parameters jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    error_message text
);

create table events (
    id bigint generated by default as identity primary key,
    analysis_id bigint not null unique references analysis_runs(id),
    event_type varchar(64) not null,
    sector varchar(64),
    country varchar(128),
    project_amount_usd numeric(20, 2),
    source_credibility numeric(6, 5) not null
        check (source_credibility between 0 and 1),
    summary text,
    created_at timestamptz not null default now()
);

create table event_companies (
    id bigint generated by default as identity primary key,
    event_id bigint not null references events(id) on delete cascade,
    company_name varchar(200) not null,
    symbol varchar(32),
    relation_type varchar(32) not null,
    relevance_score numeric(6, 5) not null
        check (relevance_score between 0 and 1),
    unique (event_id, symbol)
);

create table stock_impacts (
    id bigint generated by default as identity primary key,
    event_id bigint not null references events(id) on delete cascade,
    symbol varchar(32) not null,
    company_name varchar(200) not null,
    direction varchar(16) not null,
    probability numeric(5, 2) not null
        check (probability between 0 and 100),
    estimated_low numeric(12, 4),
    estimated_high numeric(12, 4),
    horizon varchar(64),
    relevance_score numeric(6, 5) not null
        check (relevance_score between 0 and 1),
    final_impact_score numeric(6, 5) not null
        check (final_impact_score between 0 and 1),
    explanation text,
    risk_note text,
    created_at timestamptz not null default now(),
    unique (event_id, symbol)
);

create table factor_scores (
    id bigint generated by default as identity primary key,
    impact_id bigint not null references stock_impacts(id) on delete cascade,
    factor_name varchar(80) not null,
    raw_score numeric(8, 5) not null,
    threshold numeric(8, 5) not null,
    activation numeric(8, 5) not null,
    weight numeric(8, 5) not null,
    contribution numeric(8, 5) not null,
    reason text
);

create table stock_prices (
    id bigint generated by default as identity primary key,
    symbol varchar(32) not null,
    trade_date date not null,
    close_price numeric(20, 8) not null check (close_price > 0),
    volume bigint,
    return_pct numeric(12, 8),
    source varchar(64),
    created_at timestamptz not null default now(),
    unique (symbol, trade_date)
);

create table relu_momentum_points (
    id bigint generated by default as identity primary key,
    impact_id bigint not null references stock_impacts(id) on delete cascade,
    symbol varchar(32) not null,
    point_index integer not null check (point_index >= 0),
    trade_date date,
    price numeric(20, 8) not null check (price > 0),
    return_pct numeric(12, 8) not null,
    cumulative_return numeric(12, 8) not null,
    relu_return numeric(12, 8) not null,
    relu_momentum numeric(12, 8) not null,
    threshold numeric(12, 8) not null,
    unique (impact_id, point_index)
);

create index idx_news_published_at
    on news_articles (published_at desc);
create index idx_runs_news_started_at
    on analysis_runs (news_id, started_at desc);
create index idx_events_type
    on events (event_type);
create index idx_impacts_symbol_id
    on stock_impacts (symbol, id desc);
create index idx_prices_symbol_date
    on stock_prices (symbol, trade_date desc);
create index idx_relu_impact_point
    on relu_momentum_points (impact_id, point_index);
