alter table stock_prices
    add column if not exists adjusted_close_price numeric(20, 8);

update stock_prices
set adjusted_close_price = close_price
where adjusted_close_price is null;

create index if not exists idx_prices_symbol_date_desc
    on stock_prices (symbol, trade_date desc);

create table if not exists sector_etf_mapping (
    id bigint generated by default as identity primary key,
    sector varchar(64) not null,
    etf_symbol varchar(32) not null,
    priority integer not null default 1,
    active boolean not null default true,
    unique (sector, etf_symbol)
);

insert into sector_etf_mapping (sector, etf_symbol, priority) values
    ('新能源', 'ICLN', 1),
    ('半导体', 'SOXX', 1),
    ('AI 芯片', 'QQQ', 1),
    ('金融', 'XLF', 1),
    ('能源', 'XLE', 1),
    ('生物医药', 'XBI', 1)
on conflict (sector, etf_symbol) do nothing;
