create table if not exists backtest_runs (
    id bigint generated by default as identity primary key,
    start_date date not null,
    end_date date not null,
    symbols text,
    horizons varchar(64) not null,
    model_version varchar(64) not null,
    status varchar(16) not null,
    sample_count integer not null default 0,
    result jsonb,
    error_message text,
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists backtest_samples (
    id bigint generated by default as identity primary key,
    run_id bigint not null references backtest_runs(id) on delete cascade,
    event_id bigint not null,
    impact_id bigint not null,
    symbol varchar(32) not null,
    event_time timestamptz not null,
    event_direction varchar(16) not null,
    sector varchar(64),
    final_impact_score numeric(8, 5) not null,
    relevance_score numeric(8, 5) not null,
    relu_score numeric(8, 5) not null,
    entry_price numeric(20, 8) not null,
    return_1d numeric(12, 8),
    return_3d numeric(12, 8),
    return_5d numeric(12, 8),
    return_10d numeric(12, 8),
    label_1d_up boolean,
    label_3d_up boolean,
    label_direction_correct boolean,
    created_at timestamptz not null default now()
);

create index if not exists idx_backtest_samples_run on backtest_samples(run_id);
create index if not exists idx_backtest_samples_symbol on backtest_samples(symbol, event_time);

create table if not exists model_versions (
    id bigint generated by default as identity primary key,
    model_version varchar(64) not null unique,
    model_type varchar(32) not null,
    target varchar(64) not null,
    feature_schema jsonb not null,
    weights jsonb not null,
    metrics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    active boolean not null default false
);
